name = "crypto-paste-api"
main = "src/worker.ts"
compatibility_date = "2024-06-25"

[[kv_namespaces]]
binding = "PASTES_KV"
id = "b84230dd8e4e45adbf520760f7aa272f"
preview_id = "e903f70bfe8c4dbab1838e26a68edaa6"

[vars]
ENVIRONMENT = "production"